// Lighting presets. Angles in degrees; azimuth 0 = +Z (south), 90 = +X (east).
// Colours are sRGB hex strings (converted to linear by THREE.Color).

export const TIME_PRESETS = {
  sunset: {
    label: 'Sunset',
    night: false,
    sunElevation: 3.4,
    sunAzimuth: 292,
    sky: {
      turbidity: 8,
      rayleigh: 2.8,
      mieCoefficient: 0.005,
      mieDirectionalG: 0.86,
      cloudCoverage: 0.34,
      cloudDensity: 0.55,
      cloudScale: 0.00022,
      cloudElevation: 0.55,
    },
    sunColor: '#ffab6e',
    sunIntensity: 3.2,
    hemiSky: '#94a9d6',
    hemiGround: '#4d3d2c',
    hemiIntensity: 0.85,
    fogColor: '#b98f78',
    fogSunColor: '#ff8a3a',
    fogSunStrength: 1.4,
    fogDensity: 0.00046,
    fogHeight: [4, 30, 0.9],
    horizonBlend: 0.75,
    exposure: 0.7,
    envIntensity: 1.0,
    envGround: '#2c2a22',
    bloom: { strength: 0.3, radius: 0.55, threshold: 2.2 },
    lamps: false,
    headlights: false,
  },
  day: {
    label: 'Midday',
    night: false,
    sunElevation: 52,
    sunAzimuth: 210,
    sky: {
      turbidity: 2.4,
      rayleigh: 0.9,
      mieCoefficient: 0.004,
      mieDirectionalG: 0.8,
      cloudCoverage: 0.38,
      cloudDensity: 0.6,
      cloudScale: 0.0002,
      cloudElevation: 0.5,
    },
    sunColor: '#fff4e6',
    sunIntensity: 3.6,
    hemiSky: '#bcd6ff',
    hemiGround: '#5d5a40',
    hemiIntensity: 1.1,
    fogColor: '#a9bfd8',
    fogSunColor: '#fff0d8',
    fogSunStrength: 0.25,
    fogDensity: 0.00036,
    fogHeight: [0, 40, 0.6],
    horizonBlend: 0.8,
    exposure: 0.5,
    envIntensity: 1.0,
    envGround: '#3a3a2c',
    bloom: { strength: 0.18, radius: 0.5, threshold: 3.0 },
    lamps: false,
    headlights: false,
  },
  night: {
    label: 'Night',
    night: true,
    sunElevation: 38,
    sunAzimuth: 140,
    sunColor: '#8fa8ff',
    sunIntensity: 0.32,
    hemiSky: '#23304f',
    hemiGround: '#0b0b10',
    hemiIntensity: 0.5,
    fogColor: '#0b111d',
    fogSunColor: '#1a2233',
    fogSunStrength: 0.4,
    fogDensity: 0.0008,
    fogHeight: [2, 20, 1.2],
    horizonBlend: 1,
    exposure: 1.0,
    envIntensity: 0.9,
    envGround: '#07070a',
    bloom: { strength: 0.65, radius: 0.6, threshold: 1.1 },
    lamps: true,
    headlights: true,
  },
};

export function sunDirection(preset, out) {
  const el = (preset.sunElevation * Math.PI) / 180;
  const az = (preset.sunAzimuth * Math.PI) / 180;
  return out.set(Math.sin(az) * Math.cos(el), Math.sin(el), Math.cos(az) * Math.cos(el)).normalize();
}
